config/routes.rb
Rails.application.routes.draw do
  get '/etsy/search', to: 'etsy#search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/etsy_controller.rb
class EtsyController < ApplicationController
  def search
    if params[:q]
      response = Etsy::Request.get('/listings/active', :includes => ['Images', 'Shop'], :keywords => params[:q])
      @results = JSON.parse(response.body)['results']
    end
    render :search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/etsy/search.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <header>
      <div class="entire-header">
        <div class="leftsection">
          <h1>
            <a href="https://www.etsy.com/?ref=lgo"><img src="https://www.etsy.com/assets/dist/images/etsylogo.20150106184300.png" id="etsy-logo"></a>
          </h1>
        </div>
        <div class="search-bar-wrap">
          <%= form_tag etsy_search_path, method: 'get', :id => 'search-form' do %>
            <%= text_field_tag 'search_query', params[:q], :class => "search-bar",  :placeholder => 'Search for items or shops' %>
            <%= submit_tag 'Search', :class => "search-button" %>
          <% end %>
        </div>
        <div class="browse">
          <a href ="">Browse</a>
        </div>
        <div class="right-section">
          <li id="help-button">
            <a href="https://www.etsy.com/help?ref=hdr">Help</a>
          </li>
          <li id="register">
            <a href="https://www.etsy.com/join?ref=hdr&from_page=https://www.etsy.com/search">Register</a>
          </li>
          <li id="sign-in">
            <a href="https://www.etsy.com/signin?ref=hdr&from_page=https://www.etsy.com/search">Sign In</a>
          </li>
        </div>
      </div>
    </header>

    <div class="sidebar">
    <p class="returned">Show Results For:</p>
      <h2>Item Type</h2>
      <div class="basketball">
          <li><span class="side-text" id="side-button"><a href="https://www.etsy.com/search?q=basketball">All Items</span></a></li>
          <li><span class="side-text" id="side-button"><a href="https://www.etsy.com/search/handmade?q=basketball">Handmade</span></a></li>
          <li><span class="side-text" id="side-button"><a href="https://www.etsy.com/search/vintage?q=basketball">Vintage</span></a></li>
          <li><span class="side-text" id="side-button"><a href="https://www.etsy.com/search/supplies?q=basketball">Craft Supplies</span></a></li>
      </div>
      <h3>Categories</h3>
      <div class="handmade-list">
        <li><a class="handmade-category" href="https://www.etsy.com/search/handmade?q=basketball">Handmade</a></li>
        <li><a class="little-side-buttons" href="https://www.etsy.com/search/handmade/clothing?q=basketball">Clothing</a></li>
        <li><a class="little-side-buttons" href="">Jewelry</a></li>
        <li><a class="little-side-buttons" href="">Accessories</a></li>
        <li><a class="little-side-buttons" href="">Children</a></li>
        <li><a class="little-side-buttons" href="">Art</a></li>
        <li><a class="little-side-buttons" href="">Everything Else</a></li>
        <li><a class="little-side-buttons" href="">Housewares</a></li>
        <li><a class="little-side-buttons" href="">Paper Goods</a></li>
      </div>
      <div class="vintage-list">
        <li><a class="vintage-category" href="">Vintage</a></li>
        <li><a class="little-side-buttons" href="">Clothing</a></li>
        <li><a class="little-side-buttons" href="">Collectibles</a></li>
        <li><a class="little-side-buttons" href="">Acessories</a></li>
        <li><a class="little-side-buttons" href="">Paper Ephemera</a></li>
      </div>
      <div class="craft-list">
        <li><a class="craft-category" href="">Craft Supplies</a></li>
        <li><a class="little-side-buttons" href="">Bead</a></li>
        <li><a class="little-side-buttons" href="">Commercial</a></li>
        <li><a class="little-side-buttons" href="">Fabric</a></li>
        <li><a class="little-side-buttons" href="">Scrapbooking</a></li>
      </div>
    </div>

    <div class="search-results-center">
      <% if @results %>
        <% @results.each do |x| %>
        <ol>

        <div class="itemboxes">
          <li>
          <div class="image">
          <%= link_to x['url'] do %>
            <%= image_tag x['Images'][0]['url_170x135'], size: "214x170" %>
          <% end %>
          </div>
          <div class="result-name">
            <%= x["title"] %>
          </div>
          <div class="details">
          <%= link_to x['Shop']['url'] do %>
            <div class="shopname">
            <%= "#{x['Shop']['shop_name']}" %>
            </div>
            <% end %>
          </div>
          <div class="pricing">
            <%= "$#{x["price"]} USD" %>
          </div>
          </li>
        </div>
        </ol>
          <% end %>
        <% end %>
    </div>

    <!-- <footer> -->
    <div id="footer">
      <div class="top-footer">
        <li class="region">
          <a href="https://www.etsy.com/search?q=hello#region-select"><img src="http://agconexus.agconexusinc.netdna-cdn.com/wp-content/uploads/2013/02/Globe.png" id="world-image">United States</a>
        </li>
        <li class="language">
          <a href="https://www.etsy.com/search?q=hello#language-select">English (US)</a>
        </li>
        <li class="currency">
          <a href="https://www.etsy.com/search?q=hello#currency-select">$ USD</a>
        </li>
      </div>
    </div>
      <div class="lower-footer">
        <li class="copyright">
          <p>&copy 2015 Etsy, Inc.</p>
        </li>
        <li class="terms">
          <a href="https://www.etsy.com/help/article/479/?ref=ftr">Terms</a>
        </li>
        <li class="privacy">
          <a href="https://www.etsy.com/help/article/480/?ref=ftr">Privacy</a>
        </li>
        <li class="copyright-two">
          <a href="https://www.etsy.com/help/article/482/?ref=ftr">Copyright</a>
        </li>
        <li class="ads">
          <a href="https://www.etsy.com/help/article/3293?ref=ftr">Internet Based-Ads</a>
        </li>
      </div>
    </div>
   <!-- </footer> -->
  </body>
</html>









<!-- <div class="homebutton">
          <a href="https://www.etsy.com/?ref=hdr" title="Home"><img src="http://www.veryicon.com/icon/png/System/ClearBlack/Black%20Home.png" alt="Home button"></a>
          <span class="textlink">
            <span class="testlinkcopy">
              Home
            </span>
          </span>
        <div class="favoritesbutton"
          <a href=
        </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EtsySearcher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

<!-- -->